sudo: false

language: java

jdk:
    - oraclejdk8
    - oraclejdk9

env:
  global:
  # taken first download mirror from http://maven.apache.org/
    - BASEURL=http://mirror.softaculous.com/apache/maven/maven-3/VERSION/binaries/apache-maven-VERSION-bin.tar.gz
    - FILE=apache-maven-VERSION-bin.tar.gz
    - DIR=apache-maven-VERSION/bin
  matrix:
    - VERSION=3.5.2
    - VERSION=3.3.9
    - VERSION=3.2.5

python:
  - 2.7

before_install:
  - pip install --user codecov

script:
  - wget $(echo -n $BASEURL | sed -e 's#VERSION#'$VERSION'#g')
  - tar -xvzf $(echo -n $FILE | sed -e 's#VERSION#'$VERSION'#')
  - export PATH=$(echo -n $DIR | sed -e 's#VERSION#'$VERSION'#'):$PATH

after_success:
  - codecov
